---
# zabbix-agent-urbackupuserparams tasks main file

- name: Configure user parameters
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ included_path }}/{{ item }}"
    force: yes
    backup: false
    owner: root
    group: zabbix
    mode: "0440"
  loop:
    - urbackupclient-userparams.conf
    - urbackupserver-userparams.conf
  register: copy_userparams_result

- name: Restart zabbix-agent
  when: copy_userparams_result.changed
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
